# Generated by Django 3.1.1 on 2020-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('tagline', models.TextField(verbose_name='Tagline')),
                ('speaker', models.CharField(max_length=100, verbose_name='Speaker')),
                ('topic', models.TextField(verbose_name='Topic')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('room_capacity', models.IntegerField(verbose_name='Room Capacity')),
                ('time', models.CharField(choices=[('m', 'Morning'), ('mm', 'Midmorning'), ('a', 'Afternoon')], max_length=50, verbose_name='Time')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
            ],
        ),
    ]
