# Generated by Django 3.1.1 on 2020-09-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.CharField(choices=[('m', 'Morning'), ('mm', 'Midmorning'), ('a', 'Afternoon')], max_length=50, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
