# Generated by Django 3.1.1 on 2020-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event_current_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_seat_number',
            field=models.IntegerField(default=0, verbose_name='Current Seat Number'),
        ),
    ]
