# Generated by Django 3.1.1 on 2020-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200909_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%D', verbose_name='Event Image'),
        ),
    ]
