# Generated by Django 3.1.1 on 2020-09-13 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20200913_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, through='accounts.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
