# Generated by Django 3.1.1 on 2020-09-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200915_0148'),
        ('accounts', '0012_auto_20200915_1159'),
    ]

    operations = [
    ]
