# Generated by Django 3.1.1 on 2020-09-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200915_1159'),
        ('accounts', '0011_merge_20200915_0937'),
    ]

    operations = [
    ]
