# Generated by Django 3.1.1 on 2020-09-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20200915_1943'),
        ('accounts', '0013_merge_20200915_1930'),
    ]

    operations = [
    ]
